add files with all 17 exercises from 1st JS lesson
lyppay/JS_1 pull request #1
Opened 2024-10-25 21:47 UTC by lyppay

added 2 files:
1. homework.js - with homework
2. index.html - to show results in browser console

2024-10-28 12:09 UTC, Solnick requested changes

2024-10-28 12:09 UTC, Solnick commented on homework.js
> +if (isSunny === true) {
remember that syntax for `if` statement is as follows:
```
if(<expression that evaluates to truthy>) {
 // code
}
```
so you can do 
```suggestion
if (isSunny) {
```
Because `isSunny` is already of boolean type, no need to create a new expression that checks if `true === true` or `false === true`.

2024-10-28 12:09 UTC, Solnick commented on homework.js
> +else {
```suggestion
} else {
```

2024-10-28 12:09 UTC, Solnick commented on homework.js
> +const bodyMassIndex = personWeight / (personHeightInMeters* personHeightInMeters);
```suggestion
const bodyMassIndex = personWeight / (personHeightInMeters * personHeightInMeters);
```

2024-10-28 12:09 UTC, Solnick commented on homework.js
> +if (studentScore < 0 || studentScore > 100) {
This `if` statement is very vulnerable when it comes to order of the following statements. You got it spot on :) Good job

2024-10-30 15:20 UTC, lyppay commented on homework.js
> +if (isSunny === true) {
Right, it is good idea to simplify that :)
Resolved

2024-10-30 15:20 UTC, lyppay commented on homework.js
> +const bodyMassIndex = personWeight / (personHeightInMeters* personHeightInMeters);
Resolved

2024-10-30 15:21 UTC, lyppay commented on homework.js
> +if (studentScore < 0 || studentScore > 100) {
It is great to hear that!
Thanks!

2024-10-30 15:21 UTC, lyppay commented on homework.js
> +else {
Resolved

2024-11-11 17:59 UTC, mwanago requested changes

2024-11-11 17:59 UTC, mwanago commented on homework.js
> +else if (currentMonth >=3 && currentMonth <= 5) {
`else if` should be in the same line as `}`
```
if (...) {
  ...
} else if (...) {
  ...
} else {
  ...
}
```

2024-11-11 17:59 UTC, mwanago commented on homework.js
> +console.log("--- Exercise 10 ---");
Be consistent. Either use `"` or use `'`. Personally, I always use `'` if possible. Change the entire file to incorporate that.

2024-11-11 17:59 UTC, mwanago commented on homework.js
> +if (numberToDivide !== 0) {
It's okay to divide `0` by something.
0 / 3 = 0
0 / 5 = 0

2024-11-11 17:59 UTC, mwanago commented on homework.js
> +else if (ageOfPerson < 18) {
`else if` should be in the same line as `}`
```
if (...) {
  ...
} else if (...) {
  ...
} else {
  ...
}
```

2024-11-11 18:17 UTC, lyppay commented on homework.js
> +else if (currentMonth >=3 && currentMonth <= 5) {
all else's combinations move to line which is ending 'if' condition

2024-11-11 18:17 UTC, lyppay commented on homework.js
> +console.log("--- Exercise 10 ---");
in this case I have changed ' to ", due to less amount of changes
in future I will try to use suggested '

2024-11-11 18:19 UTC, lyppay commented on homework.js
> +if (numberToDivide !== 0) {
changed

2024-11-11 18:20 UTC, lyppay commented on homework.js
> +else if (ageOfPerson < 18) {
fixed

2024-11-11 18:24 UTC, mwanago commented on homework.js
> +console.log("--- Exercise 10 ---");
I still see 49 `'` characters in this file

2024-11-11 21:36 UTC, mwanago approved these changes

2024-11-20 11:44 UTC, merged